/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Bridge.glb -t --types --keepnames --shadows -o ./app/components/models/Bridge.tsx
*/

import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { useGLTF } from '@react-three/drei';
import React from 'react';

type GLTFResult = GLTF & {
  nodes: {
    Wood_Bridge1: THREE.Mesh;
  };
  materials: {
    lambert3SG: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Bridge.glb') as GLTFResult;

  if (!nodes)
    return null;

  return (
    <group {...props} dispose={null}>
      <mesh name="Wood_Bridge1" castShadow receiveShadow geometry={nodes.Wood_Bridge1.geometry} material={materials.lambert3SG} />
    </group>
  );
}

useGLTF.preload('/Bridge.glb');
