/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Door.glb -t --types --keepnames --shadows -o ./app/components/models/Door.tsx
*/

import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { useGLTF } from '@react-three/drei';
import React from 'react';

type GLTFResult = GLTF & {
  nodes: {
    SM_ArchwaySM_Archway1_1: THREE.Mesh;
    SM_ArchwaySM_Archway1_1_1: THREE.Mesh;
    SM_ArchwaySM_Archway1_1_2: THREE.Mesh;
  };
  materials: {
    lambert2SG: THREE.MeshStandardMaterial;
    lambert4SG: THREE.MeshStandardMaterial;
    lambert3SG: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Door.glb') as GLTFResult;

  if (!nodes)
    return null;

  return (
    <group {...props} dispose={null}>
      <mesh name="SM_ArchwaySM_Archway1_1" castShadow receiveShadow geometry={nodes.SM_ArchwaySM_Archway1_1.geometry} material={materials.lambert2SG} />
      <mesh name="SM_ArchwaySM_Archway1_1_1" castShadow receiveShadow geometry={nodes.SM_ArchwaySM_Archway1_1_1.geometry} material={materials.lambert4SG} />
      <mesh name="SM_ArchwaySM_Archway1_1_2" castShadow receiveShadow geometry={nodes.SM_ArchwaySM_Archway1_1_2.geometry} material={materials.lambert3SG} />
    </group>
  );
}

useGLTF.preload('/Door.glb');
