/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Motorcycle.glb -t --types --keepnames --shadows -o ./app/components/models/Motorcycle.tsx
*/

import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { useGLTF } from '@react-three/drei';
import React from 'react';

type GLTFResult = GLTF & {
  nodes: {
    Motorcycle_mesh: THREE.Mesh;
  };
  materials: {
    blinn1SG: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Motorcycle.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh name="Motorcycle_mesh" castShadow receiveShadow geometry={nodes.Motorcycle_mesh.geometry} material={materials.blinn1SG} />
    </group>
  );
}

useGLTF.preload('/Motorcycle.glb');
