/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Sakura.glb -t --types --keepnames --shadows -o ./app/components/models/Sakura.tsx
*/

import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { useGLTF } from '@react-three/drei';
import React from 'react';

type GLTFResult = GLTF & {
  nodes: {
    ['??????????_1']: THREE.Mesh;
    ['??????????_1_1']: THREE.Mesh;
  };
  materials: {
    ['??????']: THREE.MeshStandardMaterial;
    ['???????_??????']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Sakura.glb') as GLTFResult;

  if (!nodes)
    return null;

  return (
    <group {...props} dispose={null}>
      <mesh name="??????????_1" castShadow receiveShadow geometry={nodes['??????????_1'].geometry} material={materials['??????']} />
      <mesh name="??????????_1_1" castShadow receiveShadow geometry={nodes['??????????_1_1'].geometry} material={materials['???????_??????']} />
    </group>
  );
}

useGLTF.preload('/Sakura.glb');
