/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Soju.glb -t --types --keepnames --shadows -o ./app/components/models/Soju.tsx
*/

import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { useGLTF } from '@react-three/drei';
import React from 'react';

type GLTFResult = GLTF & {
  nodes: {
    group1240572113: THREE.Mesh;
    group1799578475: THREE.Mesh;
    group513687082: THREE.Mesh;
    group517794709: THREE.Mesh;
    group400981136: THREE.Mesh;
    group1966730439: THREE.Mesh;
    group684520965: THREE.Mesh;
    group2066391043: THREE.Mesh;
    group116389814: THREE.Mesh;
    group834184757: THREE.Mesh;
    group935593738: THREE.Mesh;
    group1385677405: THREE.Mesh;
    group118863927: THREE.Mesh;
    group1161379559: THREE.Mesh;
    group279574652: THREE.Mesh;
    group1082600607: THREE.Mesh;
    group2113453419: THREE.Mesh;
    group737774451: THREE.Mesh;
  };
  materials: {
    mat10: THREE.MeshStandardMaterial;
    mat24: THREE.MeshStandardMaterial;
    mat23: THREE.MeshStandardMaterial;
    mat21: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Soju.glb') as GLTFResult;

  if (!nodes)
    return null;

  return (
    <group {...props} dispose={null}>
      <mesh name="group1240572113" castShadow receiveShadow geometry={nodes.group1240572113.geometry} material={materials.mat10} />
      <mesh name="group1799578475" castShadow receiveShadow geometry={nodes.group1799578475.geometry} material={materials.mat24} />
      <mesh name="group513687082" castShadow receiveShadow geometry={nodes.group513687082.geometry} material={materials.mat23} />
      <mesh name="group517794709" castShadow receiveShadow geometry={nodes.group517794709.geometry} material={materials.mat21} />
      <mesh name="group400981136" castShadow receiveShadow geometry={nodes.group400981136.geometry} material={materials.mat23} />
      <mesh name="group1966730439" castShadow receiveShadow geometry={nodes.group1966730439.geometry} material={materials.mat24} />
      <mesh name="group684520965" castShadow receiveShadow geometry={nodes.group684520965.geometry} material={materials.mat24} />
      <mesh name="group2066391043" castShadow receiveShadow geometry={nodes.group2066391043.geometry} material={materials.mat24} />
      <mesh name="group116389814" castShadow receiveShadow geometry={nodes.group116389814.geometry} material={materials.mat24} />
      <mesh name="group834184757" castShadow receiveShadow geometry={nodes.group834184757.geometry} material={materials.mat23} />
      <mesh name="group935593738" castShadow receiveShadow geometry={nodes.group935593738.geometry} material={materials.mat23} />
      <mesh name="group1385677405" castShadow receiveShadow geometry={nodes.group1385677405.geometry} material={materials.mat23} />
      <mesh name="group118863927" castShadow receiveShadow geometry={nodes.group118863927.geometry} material={materials.mat23} />
      <mesh name="group1161379559" castShadow receiveShadow geometry={nodes.group1161379559.geometry} material={materials.mat23} />
      <mesh name="group279574652" castShadow receiveShadow geometry={nodes.group279574652.geometry} material={materials.mat23} />
      <mesh name="group1082600607" castShadow receiveShadow geometry={nodes.group1082600607.geometry} material={materials.mat23} />
      <mesh name="group2113453419" castShadow receiveShadow geometry={nodes.group2113453419.geometry} material={materials.mat23} />
      <mesh name="group737774451" castShadow receiveShadow geometry={nodes.group737774451.geometry} material={materials.mat23} />
    </group>
  );
}

useGLTF.preload('/Soju.glb');
