/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Torii.glb -t --types --keepnames --shadows -o ./app/components/models/Torii.tsx
*/

import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { useGLTF } from '@react-three/drei';
import React from 'react';

type GLTFResult = GLTF & {
  nodes: {
    ['Node-Mesh']: THREE.Mesh;
    ['Node-Mesh_1']: THREE.Mesh;
  };
  materials: {
    mat23: THREE.MeshStandardMaterial;
    mat14: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Torii.glb') as GLTFResult;

  if (!nodes)
    return null;

  return (
    <group {...props} dispose={null}>
      <mesh name="Node-Mesh" castShadow receiveShadow geometry={nodes['Node-Mesh'].geometry} material={materials.mat23} />
      <mesh name="Node-Mesh_1" castShadow receiveShadow geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat14} />
    </group>
  );
}

useGLTF.preload('/Torii.glb');
